### ISSUE TITLE
password not included in signup request payload

### ISSUE THREAD

**Issue by kamtoeddy** [saurabhje/FastCode#1]
Just tried the app. Love it but can't register
- filled name and email fields
- the passwords were generated by Firefox password manager
- tried to register and the message in the toaster said "Password must be non-empty."
- manually updated the passwords and the same error occurred
- inspecting the network tab showed that the password in the request payload was an empty string

This happened on:
 - OS: Ubuntu 24.04 LTS
 - Browser: Firefox

**Comment by saurabhje** [comment]
Hey Eddy, 
I couldn't reproduce the bug, although I suspect it occurred due to incorrect state management on my part.
I made some changes to the states, hoping that would fix the problem.

Please let me know if it resolves your issue.

**Comment by kamtoeddy** [comment]
Hi,
this issue has been resolved for signup but happens at login.
My email has already been verified but when I try to log in, the password is not sent to the server in the payload
